---
# yamllint disable rule:line-length
###############################################################################
# Prepare
###############################################################################
# Testing requires a valid PFX certificate. Generate a test certificate valid
# for 10 years (all default values, password: 'test'):
#
# Place in cache/test.pfx.
#
# Reference:
# * https://gist.github.com/rquackenbush/53ff432567699b21c86f3360fb4ec7f0
# * https://superuser.com/questions/226192/avoid-password-prompt-for-keys-and-prompts-for-dn-information
# yamllint enable rule:line-length

- name: 'Enable SSL | prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Enable SSL | prepare | generate cache location'
      ansible.builtin.set_fact:
        _test_cache:
          '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/cache'

    - name: 'Enable SSL | prepare | create cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Enable SSL | prepare | create cache'

    # TODO(role): change to version when released. Potentially may break.
    - name: 'Enable SSL | prepare | check 2.0.0.787'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: 'Enable SSL | prepare | cache 2.0.0.787'
        test_dest: 'Whisparr.develop.2.0.0.787.linux-core-x64.tar.gz'
        test_url: '{{
            "https://whisparr.servarr.com/v1/update/nightly/" ~
            "updatefile?os=linux&runtime=netcore&arch=x64"
          }}'
        test_mode: '0640'

    - name: 'Enable SSL | prepare | generate test certificate'
      ansible.builtin.command:
        argv:
          - 'openssl'
          - 'req'
          - '-new'
          - '-newkey'
          - 'rsa:4096'
          - '-nodes'
          - '-subj'
          - '/C=US/ST=NY/L=NY/O=test/CN=test.example.com'
          - '-keyout'
          - '{{ _test_cache }}/test.key'
          - '-out'
          - '{{ _test_cache }}/test.csr'
        creates: '{{ _test_cache }}/test.key'

    - name: 'Enable SSL | prepare | sign test certificate'
      ansible.builtin.command:
        argv:
          - 'openssl'
          - 'x509'
          - '-req'
          - '-sha256'
          - '-days'
          - '3650'
          - '-in'
          - '{{ _test_cache }}/test.csr'
          - '-signkey'
          - '{{ _test_cache }}/test.key'
          - '-out'
          - '{{ _test_cache }}/test.pem'
        creates: '{{ _test_cache }}/test.pem'

    - name: 'Enable SSL | prepare | pack PFX certificate'
      ansible.builtin.command:
        argv:
          - 'openssl'
          - 'pkcs12'
          - '-export'
          - '-in'
          - '{{ _test_cache }}/test.pem'
          - '-inkey'
          - '{{ _test_cache }}/test.key'
          - '-out'
          - '{{ _test_cache }}/test.pfx'
          - '-passout'
          - 'pass:test'
        creates: '{{ _test_cache }}/test.pfx'

- name: 'Enable SSL | prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Enable SSL | prepare | add rsync package for synchronize'
      ansible.builtin.apt:
        name: 'rsync'
        state: 'present'
