---
- name: 'Enable SSL | verify | SSL enabled'
  hosts: 'whisparr-debian-13-enable_ssl'
  gather_facts: false
  tasks:
    - name: 'Enable SSL | verify | SSL enabled | config.xml'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Enable SSL | verify | SSL enabled | config.xml'
        test_src: 'files/config_ssl.xml'
        test_file: '/data/whisparr/config/config.xml'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0600'

    - name: >-
        Enable SSL | verify | SSL enabled |
        /data/whisparr/config/whisparr.pfx
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: >-
          Enable SSL | verify | SSL enabled |
          /data/whisparr/config/whisparr.pfx
        test_file: '/data/whisparr/config/whisparr.pfx'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0640'
        test_state: 'file'

- name: 'Enable SSL | verify | SSL toggled'
  hosts: 'whisparr-debian-13-enable_ssl-toggle'
  gather_facts: false
  tasks:
    - name: 'Enable SSL | verify | SSL toggled | config.xml'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Enable SSL | verify | SSL toggled | config.xml'
        test_src: 'files/config_toggle.xml'
        test_file: '/data/whisparr/config/config.xml'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0600'

    - name:
        'Enable SSL | verify | SSL toggled | /data/whisparr/config/whisparr.pfx'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: >-
          Enable SSL | verify | SSL toggled |
          /data/whisparr/config/whisparr.pfx
        test_file: '/data/whisparr/config/whisparr.pfx'
        test_owner: '{{ omit }}'
        test_group: '{{ omit }}'
        test_mode: '{{ omit }}'
        test_state: 'absent'
