---
# yamllint disable rule:line-length
- name: 'Enable SSL | verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Enable SSL | verify | gather service status'
      ansible.builtin.service_facts:

    # Whisparr will fail if configuration is bad (r_pufky.srv.systemd)
    - name: 'Enable SSL | verify | assert whisparr.service active'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"whisparr.service" in ansible_facts.services'
          - 'ansible_facts["services"]["whisparr.service"]["state"] == "running"'
        fail_msg: 'whisparr.service should be enabled and running.'

- name: 'Enable SSL | verify | SSL enabled'
  hosts: 'whisparr-debian-12-enable_ssl'
  gather_facts: false
  tasks:
    - name: 'Enable SSL | verify | SSL enabled | config.xml'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Enable SSL | verify | SSL enabled | config.xml'
        test_src: 'files/config_ssl.xml'
        test_file: '/var/lib/whisparr/config.xml'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0600'

    - name: >-
        Enable SSL | verify | SSL enabled |
        /var/lib/whisparr/whisparr.pfx
      ansible.builtin.include_role:
        name: 'r_pufky.srv.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: >-
          Enable SSL | verify | SSL enabled |
          /var/lib/whisparr/whisparr.pfx
        test_file: '/var/lib/whisparr/whisparr.pfx'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0640'
        test_state: 'file'

- name: 'Enable SSL | verify | SSL toggled'
  hosts: 'whisparr-debian-12-enable_ssl-toggle'
  gather_facts: false
  tasks:
    - name: 'Enable SSL | verify | SSL toggled | config.xml'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Enable SSL | verify | SSL toggled | config.xml'
        test_src: 'files/config_toggle.xml'
        test_file: '/var/lib/whisparr/config.xml'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0600'

    - name: 'Enable SSL | verify | SSL toggled | /var/lib/whisparr/whisparr.pfx'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: >-
          Enable SSL | verify | SSL toggled |
          /var/lib/whisparr/whisparr.pfx
        test_file: '/var/lib/whisparr/whisparr.pfx'
        test_owner: '{{ omit }}'
        test_group: '{{ omit }}'
        test_mode: '{{ omit }}'
        test_state: 'absent'
