---
# yamllint disable rule:line-length
- name: 'Live API test | prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Live API test | prepare | API TESTING NOT ENABLED'
      when: not whisparr_live_api_enable
      ansible.builtin.fail:
        msg: |
          TEST WILL NOT EXECUTE UNLESS IT IS EXPLICITLY ENABLED.

          Set whisparr_live_api_enable=true to test live API commands.

            molecule test -s live_api_test -- -v -e 'whisparr_live_api_enable=true'

          Additionally, a github token may be provided to test authenticated API use:

            molecule test -s live_api_test -- -v -e 'whisparr_live_api_enable=true,github_personal_access_token={TOKEN}'
