---
- name: 'Live API test | verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Live API test | verify | gather service status'
      ansible.builtin.service_facts:

    - name: 'Live API test | verify | config.xml'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Live API test | verify | config.xml'
        test_src: 'files/config.xml'
        test_file: '/var/lib/whisparr/config.xml'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0600'

    # Whisparr will fail if configuration is bad (r_pufky.deb.systemd)
    - name: 'Live API test | verify | assert whisparr.service active'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"whisparr.service" in ansible_facts.services'
          - 'ansible_facts["services"]["whisparr.service"]["state"] == "running"'  # yamllint disable-line rule:line-length
        fail_msg: 'whisparr.service should be enabled and running.'

    - name: 'Live API test | verify | /var/lib/whisparr'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Live API test | verify | /var/lib/whisparr'
        test_file: '/var/lib/whisparr'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0775'
        test_state: 'directory'

    - name: 'Live API test | verify | /var/lib/whisparr/update_script'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Live API test | verify | /var/lib/whisparr/update_script'
        test_file: '/var/lib/whisparr/update_script'
        test_owner: '{{ omit }}'
        test_group: '{{ omit }}'
        test_mode: '{{ omit }}'
        test_state: 'absent'

    - name: 'Live API test | verify | /var/lib/whisparr/whisparr.pfx'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Live API test | verify | /var/lib/whisparr/whisparr.pfx'
        test_file: '/var/lib/whisparr/whisparr.pfx'
        test_owner: '{{ omit }}'
        test_group: '{{ omit }}'
        test_mode: '{{ omit }}'
        test_state: 'absent'

    - name: 'Live API test | verify | /data/media'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Live API test | verify | /data/media'
        test_file: '/data/media'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0755'
        test_state: 'directory'
