---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | config.xml'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | config.xml'
        test_src: 'files/config.xml'
        test_file: '/data/whisparr/config/config.xml'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0600'
        test_diff: true

    - name: 'Verify | /data/whisparr/config'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Verify | /data/whisparr/config'
        test_file: '/data/whisparr/config'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0775'
        test_state: 'directory'
        test_diff: true

    - name: 'Verify | /data/whisparr/config/update_script'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Verify | /data/whisparr/config/update_script'
        test_file: '/data/whisparr/config/update_script'
        test_owner: '{{ omit }}'
        test_group: '{{ omit }}'
        test_mode: '{{ omit }}'
        test_state: 'absent'
        test_diff: true

    - name: 'Verify | /data/whisparr/config/whisparr.pfx'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Verify | /data/whisparr/config/whisparr.pfx'
        test_file: '/data/whisparr/config/whisparr.pfx'
        test_owner: '{{ omit }}'
        test_group: '{{ omit }}'
        test_mode: '{{ omit }}'
        test_state: 'absent'
        test_diff: true

    - name: 'Verify | /data/media'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Verify | /data/media'
        test_file: '/data/media'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0755'
        test_state: 'directory'
        test_diff: true
