---
###############################################################################
# Configure Services
###############################################################################
# Filetree returns a dict (instead of a list of dict) for one element. Use
# query to guarantee a list result.
#
# MediaCover (metadata) directory is Multi-GB. Safe to delete but will cause
# large metadata downloads on new version if not migrated with databases.
# Exclude from removal during configuration sync.

- name: '{{ "Config | filesystem | set " ~ whisparr___app._var_d }}'
  when: whisparr__cfg._d | length > 0
  block:
    - name: 'Config | filetree | set managed directories'
      ansible.builtin.file:
        path: '{{ whisparr___app._var_d ~ "/" ~ item.path }}'
        owner: '{{ whisparr__srv._user }}'
        group: '{{ whisparr__srv._group }}'
        mode: '0750'
        state: 'directory'
      loop: '{{ query("community.general.filetree", whisparr__cfg._d) }}'
      loop_control:
        label: '{{ item.path }}'
      when: item.state == 'directory'

    - name: 'Config | filetree | set managed files'
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: '{{ whisparr___app._var_d ~ "/" ~ item.path }}'
        owner: '{{ whisparr__srv._user }}'
        group: '{{ whisparr__srv._group }}'
        mode: '0640'
      loop: '{{ query("community.general.filetree", whisparr__cfg._d) }}'
      loop_control:
        label: '{{ item.path }}'
      when: item.state == 'file'

    - name: 'Config | filesystem | query remote files'
      ansible.builtin.find:
        paths: '{{ whisparr___app._var_d }}'
        file_type: 'any'
        hidden: true
        recurse: true
        excludes: 'MediaCover'  # Ignore MediaCover to prevent deletion.
      register: whisparr__remote

    - name: 'Config | filetree | remove unmanaged files and directories'
      ansible.builtin.file:
        path: '{{ item.path }}'
        state: 'absent'
      loop:
        '{{ whisparr__remote.files | sort(attribute="path", reverse=true) }}'
      loop_control:
        label: '{{ item.path }}'
      when: >
        item.path not in
        (
          query("community.general.filetree", whisparr__cfg._d) |
          map(attribute='path') |
          map('regex_replace', '^', whisparr___app._var_d ~ "/") | list
        )

- name: '{{ "Config | filesystem | query " ~ whisparr___app._var_d }}'
  when: whisparr__cfg._d | length == 0
  ansible.builtin.find:
    paths: "{{ whisparr___app._var_d }}"
    recurse: false  # Don't need to enumerate sub-directories to remove.
    hidden: true
  register: whisparr__cmd

- name: '{{ "Config | filesystem | clear " ~ whisparr___app._var_d }}'
  when: whisparr__cfg._d | length == 0
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ whisparr__cmd.files }}"
