---
###############################################################################
# Install
###############################################################################
# Install specified version from github release. Use custom service according
# to Linux FHS standards:
#
# Type    | Perms               | Path
# --------|---------------------|-------
# Runtime | 0750/0640 SRV:SRV   | /var/opt/whisparr
#
# Installation notes:
# * *arr expects all configuration data to reside in a single directory: DB's,
#   config, and metadata.
#     Resolution: Place all config data within /var/opt/whisparr.
#
# Reference:
# * https://github.com/Lidarr/Lidarr/tree/develop/distribution/debian

- name: 'Install | filesystem | set system directories'
  ansible.builtin.file:
    path: '{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'
  loop:
    - '{{ whisparr___app._src_dir }}'

- name: 'Install | filesystem | set service directories'
  ansible.builtin.file:
    path: '{{ item }}'
    owner: '{{ whisparr__srv._user }}'
    group: '{{ whisparr__srv._group }}'
    mode: '0755'
    state: 'directory'
  loop:
    - '{{ whisparr___app._var_dir }}'

- name: 'Install | packages'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.apt'
  vars:
    apt_packages:
      - '{{ whisparr___packages }}'
    apt_srv_package_update_cache: true

- name: 'Install | filesystem | find previous installations'
  ansible.builtin.find:
    paths: '{{ whisparr__cfg._src_dir }}'
    file_type: 'directory'
    recurse: false
    excludes:
      - '{{ whisparr__cfg._version }}'
  register: whisparr__cmd

- name: 'Install | filesystem | remove previous installations'
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: 'absent'
  loop: '{{ whisparr__cmd.files }}'
  loop_control:
    label: '{{ item.path }}'

- name: 'Install | url | 🗘 Whisparr (~1 minute) 🗘'
  when: not (url_inject_enable | default(false))
  ansible.builtin.get_url:
    url: '{{ whisparr__cfg._url }}'
    dest: '{{ "/tmp/" ~ whisparr__cfg._package }}'
    force: false
    owner: 'root'
    group: 'root'
    mode: '0644'
    headers:
      Authorization: '{{ whisparr__srv._token | default(omit) }}'
  register: whisparr__cmd
  until: whisparr__cmd is succeeded

- name: '{{ "Install | filesystem | set " ~ whisparr__cfg._app }}'
  ansible.builtin.file:
    path: '{{ whisparr__cfg._app }}'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'

- name: 'Install | filesystem | unpack Whisparr'
  ansible.builtin.unarchive:
    creates: '{{ whisparr__cfg._app ~ "/Whisparr" }}'
    src: '{{ "/tmp/" ~ whisparr__cfg._package }}'
    remote_src: true
    dest: '{{ whisparr__cfg._app }}'
    owner: 'root'
    group: 'root'
    mode: 'a-st'
    extra_opts: ['--strip-components=1']

- name: '{{ "Install | filesystem | set " ~ whisparr__cfg._service }}'
  ansible.builtin.template:
    src: 'systemd/whisparr.service.j2'
    dest: '{{ whisparr__cfg._service }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
