---
- name: 'Prep'
  ansible.builtin.include_tasks: 'prep.yml'

- name: 'Backup'
  when: whisparr_flg_backup
  ansible.builtin.include_tasks: 'backup.yml'

- name: 'Restore'
  when: whisparr_flg_restore
  ansible.builtin.include_tasks: 'restore.yml'

- name: 'Maintenance'
  when: whisparr_flg_maintenance
  ansible.builtin.import_tasks: 'maintenance.yml'

- name: 'Install'
  when: whisparr_flg_install
  ansible.builtin.include_tasks: 'install.yml'

- name: 'Config'
  when: whisparr_flg_config
  ansible.builtin.include_tasks: 'config.yml'

- name: 'Start'
  ansible.builtin.include_tasks: 'start.yml'
