---
- name: 'Annotate'
  ansible.builtin.include_tasks: 'annotate.yml'
- name: 'Prep'
  ansible.builtin.include_tasks: 'prep.yml'
- name: 'Install'
  ansible.builtin.include_tasks: 'install.yml'
- name: 'Config'
  ansible.builtin.include_tasks: 'config.yml'
- name: 'Validate'
  ansible.builtin.include_tasks: 'validate.yml'
