---
# yamllint disable rule:line-length
###############################################################################
# Whisparr Nightly Binary
###############################################################################
# After release, revert back to standard *arr services, like sonarr or radarr.
#
# Inject nightly tarball build and run github role with the archive
# pre-existing; this will install the build without requiring a manual
# download and build. Use the pre-compiled binary URL from the installation
# script.
#
# Effectively, this is copy of github/tasks/download.yml specifically targeting
# the static nightly binary URL; this is always live against the github API.
#
# TODO(role): remove this and revert to standard *arr (sonarr, radarr) process
#     when release happens.
#
# Generates:
#   _whisparr_archive: str - path to local archive.
#   _whisparr_target: str - whisparr target version.
#
# Reference:
# * https://github.com/Servarr/Wiki/blob/master/servarr/servarr-install-script.sh

- name: 'Nightly binary | set version'
  ansible.builtin.set_fact:
    _whisparr_target: '{{ now(utc=true, fmt="%Y-%m-%d") }}'

- name: 'Nightly binary | generate locations'
  ansible.builtin.set_fact:
    _whisparr_archive: '/tmp/{{ whisparr_role_github_repo }}-{{ _whisparr_target }}.{{ whisparr_role_github_repo_archive_type }}'
    _whisparr_target_url: 'https://whisparr.servarr.com/v1/update/nightly/updatefile?os=linux&runtime=netcore&arch=x64'

- name: 'Prep | check archive location'
  ansible.builtin.stat:
    path: '{{ _whisparr_archive }}'
  register: _whisparr_archive_stat

- name: 'Install | {{ whisparr_role_github_repo }} {{ _whisparr_target }}'  # noqa name[template] show full repo version
  when: not _whisparr_archive_stat.stat.exists
  ansible.builtin.get_url:
    url: '{{ _whisparr_target_url }}'
    dest: '{{ _whisparr_archive }}'
    owner: '{{ whisparr_user }}'
    group: '{{ whisparr_group }}'
    mode: 'a-st,o-rwx'
  register: _whisparr_download
  until: _whisparr_download is succeeded
  retries: 5
  delay: 2
