---
###############################################################################
#  Pre Execution Tasks
###############################################################################
# Only use data annotations in role after merging role, defaults, runtime data.
# Service may not exist if first install.
#
# *arr services use the same codebase; any bugs or fixes should be checked for
# all related services.

- name: 'Prep | fact | record start time'
  ansible.builtin.set_fact:
    whisparr__srv: "{{ whisparr___release | r_pufky.data.v3(

        _start=now(utc=True, fmt='%Y-%m-%dT%H%M%S'),
        _user=whisparr_srv_user,
        _group=whisparr_srv_group,
      ) }}"
    whisparr__cfg: "{{ whisparr___app | r_pufky.data.v3(

        _version=whisparr_srv_version,
        _package='Whisparr.' ~ whisparr_srv_version[1:] ~ '.linux-x64.tar.gz',
        _app='/opt/whisparr/src/' ~ whisparr_srv_version,
        _url=(
          whisparr___repo_url ~ whisparr_srv_version ~ '/' ~
          'Whisparr.' ~ whisparr_srv_version[1:] ~ '.linux-x64.tar.gz'
        ),
        _dir=whisparr_cfg_dir | regex_replace('\\/$', ''),
        _backup_dir=whisparr_cfg_backup_dir | regex_replace('\\/$', ''),
        _backup_metadata=whisparr_cfg_backup_metadata,
      ) }}"

- name: 'Prep | assert | backup enabled and location defined'
  when: whisparr_flg_backup
  ansible.builtin.assert:
    quiet: true
    that:
      - whisparr__cfg._backup_dir | length > 0
    fail_msg: |

      ✘ Backup location not set.
      Backups enabled but no backup location defined.

      whisparr_flg_backup: {{ whisparr_flg_backup }}
      whisparr_cfg_backup_dir: {{ whisparr__cfg._backup_dir }}

- name: 'Prep | assert | restore enabled and location defined'
  when: whisparr_flg_restore
  ansible.builtin.assert:
    quiet: true
    that:
      - whisparr__cfg._backup_dir | length > 0
    fail_msg: |

      ✘ Backup location not set.
      Backups enabled but no backup location defined.

      whisparr_flg_restore: {{ whisparr_flg_restore }}
      whisparr_cfg_backup_dir: {{ whisparr__cfg._backup_dir }}

- name: 'Prep | assert | config enabled and source defined'
  when: whisparr_flg_config
  ansible.builtin.assert:
    quiet: true
    that:
      - whisparr__cfg._dir | length > 0
    fail_msg: |

      ✘ Config source not set.
      Config source enabled but no config source defined.

      whisparr_flg_config: {{ whisparr_flg_config }}
      whisparr_cfg_dir: {{ whisparr__cfg._dir }}

- name: '{{ "Prep | account | query user " ~ whisparr__srv._user }}'
  ansible.builtin.command: '{{ "id " ~ whisparr__srv._user }}'
  failed_when: false
  register: whisparr__cfg_check
  changed_when: whisparr__cfg_check.rc > 0

- name: '{{ "Prep | account | query group " ~ whisparr__srv._group }}'
  ansible.builtin.command: '{{ "groups " ~ whisparr__srv._group }}'
  failed_when: false
  register: whisparr__group_check
  changed_when: whisparr__group_check.rc > 0

- name: '{{ "Prep | account | create group " ~ whisparr__srv._group }}'
  when: whisparr__group_check.rc != 0
  ansible.builtin.group:
    gid: '{{ whisparr___group.gid }}'
    name: '{{ whisparr___group.name }}'
    state: 'present'

- name: '{{ "Prep | account | create user " ~ whisparr__srv._user }}'
  when: whisparr__cfg_check.rc != 0
  ansible.builtin.user:
    name: '{{ whisparr___user.name }}'
    group: '{{ whisparr___user.group }}'
    uid: '{{ whisparr___user.uid }}'
    shell: '{{ whisparr___user.shell }}'
    home: '{{ whisparr___user.home }}'
    create_home: '{{ whisparr___user.create_home }}'
    password: '{{ whisparr___user.password }}'
    password_lock: '{{ whisparr___user.password_lock }}'
    update_password: '{{ whisparr___user.update_password }}'
    expires: '{{ whisparr___user.expires }}'
    system: '{{ whisparr___user.system }}'

# Pre-existing users may have a different UID/GID/Home.
- name: '{{ "Prep | account | enumerate " ~ whisparr__srv._user }}'
  ansible.builtin.user:
    name: '{{ whisparr__srv._user }}'
  check_mode: true
  changed_when: false
  register: whisparr__cfg_query

- name: 'Prep | fact | parse service UID/GID'
  ansible.builtin.set_fact:
    whisparr__cfg: "{{ whisparr__cfg | r_pufky.data.v3(

        _uid=whisparr__cfg_query.uid,
        _gid=whisparr__cfg_query.group,
      ) }}"

- name: 'Prep | systemd | stop whisparr.service'
  ansible.builtin.systemd:
    name: 'whisparr.service'
    state: 'stopped'
  failed_when: false
