---
- name: 'Prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Prepare | import role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name: 'Prepare | cache'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Prepare cache'

    - name: '{{  "Prepare | cache | Whisparr " ~ whisparr___app._version }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'cache_url.yml'
      vars:
        test_name:
          '{{  "Prepare | cache | Whisparr " ~ whisparr___app._version }}'
        test_dest: '{{ whisparr___app._package }}'
        test_url: '{{ whisparr___app._url }}'
        test_mode: '0640'

- name: 'Prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Prepare | import role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name: 'Prepare | inject | cached packages'
      when: (url_inject_enable | default(false))
      ansible.builtin.copy:
        src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/molecule/cache/" ~
            whisparr___app._package
          }}'
        dest: '{{ "/tmp/" ~ whisparr___app._package }}'
        owner: 'root'
        group: 'root'
        mode: '0644'

    # Install base to verify autogenerated config.xml works.
    - name: 'Converge | role | r_pufky.arr.whisparr (autogenerated config.xml)'
      ansible.builtin.include_role:
        name: 'r_pufky.arr.whisparr'
