---
- name: 'Default | prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Default | prepare | create cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Default | prepare | create cache'

    # TODO(role): change to version when released. Potentially may break.
    - name: 'Default | prepare | check 2.0.0.787'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: 'Default | prepare | cache 2.0.0.787'
        test_dest: 'Whisparr.develop.2.0.0.787.linux-core-x64.tar.gz'
        test_url: '{{
            "https://whisparr.servarr.com/v1/update/nightly/" ~
            "updatefile?os=linux&runtime=netcore&arch=x64"
          }}'
        test_mode: '0640'

- name: 'Default | prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | prepare | add rsync package for synchronize'
      ansible.builtin.apt:
        name: 'rsync'
        state: 'present'
