---
- name: 'Update mechanisms | converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Update mechanisms | converge | apply r_pufky.srv.whisparr'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.whisparr'

- name: 'Update mechanisms | converge | toggle updates'
  hosts: 'whisparr-debian-12-update_mechanisms-toggle'
  gather_facts: false
  tasks:
    - name: >-
        Update mechanisms | converge | toggle updates |
        apply r_pufky.srv.whisparr
      ansible.builtin.include_role:
        name: 'r_pufky.srv.whisparr'
      vars:
        whisparr_cfg_update_mechanism: true
