---
# yamllint disable rule:line-length
- name: 'Update mechanisms | prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Update mechanisms | prepare | add rsync package for synchronize'
      ansible.builtin.apt:
        name: 'rsync'
        state: 'present'
