---
- name: 'Update mechanisms | prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Update mechanisms | prepare | generate cache location'
      ansible.builtin.set_fact:
        _test_cache:
          '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/cache'

    - name: 'Update mechanisms | prepare | create cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Update mechanisms | prepare | create cache'

    - name: 'Prepare | parse test version'
      ansible.builtin.set_fact:
        test_version: '2.0.0.1250'

    # TODO(role): Change to version when released. Potentially may break.
    - name: '{{ "Prepare | cache " ~ test_version }}'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: '{{ "Prepare | cache " ~ test_version }}'
        test_dest: '{{
            "Whisparr.develop." ~ test_version ~ ".linux-core-x64.tar.gz"
          }}'
        test_url: '{{
            "https://whisparr.servarr.com/v1/update/nightly/" ~
            "updatefile?os=linux&runtime=netcore&arch=x64"
          }}'
        test_mode: '0640'

- name: 'Update mechanisms | prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Update mechanisms | prepare | add rsync package for synchronize'
      ansible.builtin.apt:
        name: 'rsync'
        state: 'present'
