---
- name: 'Update mechanisms | verify | script enabled'
  hosts: 'whisparr-debian-13-update_mechanisms'
  gather_facts: false
  tasks:
    - name: 'Update mechanisms | verify | script enabled | config.xml'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Enable SSL | verify | script enabled | config.xml'
        test_src: 'files/config_script.xml'
        test_file: '/data/whisparr/config/config.xml'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0600'

    - name: >-
        Update mechanisms | verify | script enabled |
        /data/whisparr/config/update_script
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: >-
          Update mechanisms | verify | script enabled |
          /data/whisparr/config/update_script
        test_file: '/data/whisparr/config/update_script'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0750'
        test_state: 'file'

- name: 'Update mechanisms | verify | script toggled'
  hosts: 'whisparr-debian-13-update_mechanisms-toggle'
  gather_facts: false
  tasks:
    - name: 'Update mechanisms | verify | script toggled | config.xml'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Update mechanisms | verify | script toggled | config.xml'
        test_src: 'files/config_toggle.xml'
        test_file: '/data/whisparr/config/config.xml'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0600'

    - name: >-
        Update mechanisms | verify | script toggled |
        /data/whisparr/config/update_script
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: >-
          Update mechanisms | verify | script toggled |
          /data/whisparr/config/update_script
        test_file: '/data/whisparr/config/update_script'
        test_owner: '{{ omit }}'
        test_group: '{{ omit }}'
        test_mode: '{{ omit }}'
        test_state: 'absent'
